{ pkgs, ... }:
{
  home.packages = (
    with pkgs;
    [
      aerc
      cachix
      colima
      docker
      docker-compose
      eza
      fd
      ffmpeg
      file
      gcc
      gimp
      gnumake
      goose
      google-chrome
      gtrash
      inkscape
      jetbrains.datagrip
      jetbrains.goland
      jq
      just
      killall
      kubectl
      lazydocker
      lazygit
      less
      lsof
      man-pages
      mkalias
      nano
      nil
      nix-info
      nixd
      nixfmt-rfc-style
      nixpkgs-fmt
      obsidian
      onefetch
      openssl
      postman
      programmer-calculator
      protobuf
      python3
      python312Packages.googleapis-common-protos
      python312Packages.ipython
      raycast
      ripgrep
      sd
      telegram-desktop
      tldr
      tmate
      todo
      toipe
      tree
      ttyper
      unzip
      wget
      xdg-utils
      yazi
      yt-dlp-light
      zed
    ]
  );
}
