[env]
TERM="xterm-256color"

[window]
padding.x = 10
padding.y = 10

dimensions.columns = 140
dimensions.lines = 32

decorations = "Buttonless"

opacity = 0.80
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 16


