[env]
TERM = "xterm-256color"

[window]
dimensions.columns = 140
dimensions.lines = 33

padding.x = 20
padding.y = 20

decorations = "Buttonless"
opacity = 0.92
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
builtin_box_drawing = true
# size = 22.0

[shell]
program = "/usr/bin/zsh"
